#!/usr/bin/env bash
#credit to thePrimeagen

getopts ":a" opt;
tmux_config="/home/eeby/.tmux.conf"
p=$(pwd)

if [[ $opt -eq "a" ]]; then
    if [[ $# -eq 1 ]]; then
        echo "Usage: tmuxSessionizer -a [prefix key]"
        exit 0
    fi

    cmd='bind-key -r '
    cmd+="$2"
    cmd+=' run-shell "~/dotfiles_linux/scripts/tmux-sessionizer '
    cmd+=${p}
    cmd+="/"
    cmd+='"'
    echo ${cmd}
    

    if grep -Fxq "$cmd" "$tmux_config"; then
        echo "Binding already in config"
    else
        echo "creating binding"
        echo ${cmd} >> ${tmux_config}
    fi
    
    exit 0
fi

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find  ~/ ~/classes/ ~/dotfiles_linux/dotfiles/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
